const ge_mri_gesys_schema = {
  equipment_id: null,
  time_stamp: null,
  num_1: null,
  num_2: null,
  month: null,
  day: null,
  host_time: null,
  year: null,
  num_3: null,
  num_4: null,
  mroc: null,
  data_1: null,
  num_5: null,
  data_2: null,
  server_name: null,
  exception_class: null,
  task_id: null,
  time_2: null,
  object: null,
  sr_group: null,
  en: null,
  host_dateTime: null,
};

const siemens_ct_mri = {
  equipment_id: null,
  host_state: null,
  host_date: null,
  host_time: null,
  source_group: null,
  type_group: null,
  text_group: null,
  domain_group: null,
  id_group: null,
  month: null,
  day: null,
  year: null,
  host_dateTime: null,
};

const philips_ct_eal_schema = {
    equipment_id: null,
    line: null,
    err_type: null,
    tmstamp: null,
    file: null,
    datatype: null,
    param1: null,
    errnum: null,
    info: null,
    dtime: null,
    ealtime: null,
    lognumber: null,
    param2: null,
    vxwerrno: null,
    controller: null,
    host_dateTime: null
}

module.exports = { ge_mri_gesys_schema, siemens_ct_mri, philips_ct_eal_schema };
